### ISSUE TITLE
Mismatch information about Pool3 ~ Pool5

### ISSUE THREAD

**Issue by JackieMium** [janklocke/Urine-single-cell-sequencing-AKI#1]
Hi! I've read your paper and congrats on your excellent work! Howeer I've found a typo, which I PRed, and also spotted something mismatch in meta data about samples.

In the [Urine_AKI_barcode_list.csv](https://github.com/janklocke/Urine-single-cell-sequencing-AKI/blob/main/Urine_AKI_barcode_list.csv) file we have:

```
  Barcode CD298B0251 CD298B0252 CD298B0253 CD298B0254                                                                                                                                                                                   
1   Pool1       P008       P009       P010       P012                                                                                                                                                                                   
2   Pool2       P013       P014       P015       P016                                                                                                                                                                                   
3   Pool3       P048       P050       P052       P059                                                                                                                                                                                   
4   Pool4       P048       P054       P060                                                                                                                                                                                              
5   Pool5       P051       P053       P058       P059                                                                                                                                                                                   
6   Pool6       P116       P118       P119       P120
```

`P048` is in `Pool3` and `Pool4`, `P059` in `Pool3` and `Pool5`.

And then according to [GSE199321](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE199321) we get:
[GSM5969961](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5969961) 

```
patients P0049; P0050; P0052; P0059
```

and [GSM5969963](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5969963) 

```
patients P0051; P0053; P0058; P0061
```

I believe `GSM5969961` and `GSM5969963` are `Pool3` and `Pool5` respectively. However, patient IDs don't match. This mismatch causes an error at line 221~228 in `01_AKI_Urine_Sediment_Demultiplexing_pooled_samples_script.R`:

https://github.com/janklocke/Urine-single-cell-sequencing-AKI/blob/8f3178e6f07848881c01e400d0c3e7f4c7711309/01_AKI_Urine_Sediment_Demultiplexing_pooled_samples_script.R#L221-L228

because when the loop enters `Pool4` there is nothing in "CD298B0254", so the loop throws an error.

And in `02_AKI_Urine_Sediment_SO_script.R` from line 126~141:

https://github.com/janklocke/Urine-single-cell-sequencing-AKI/blob/8f3178e6f07848881c01e400d0c3e7f4c7711309/02_AKI_Urine_Sediment_SO_script.R#L126-L141 

I hope you can check this and reply. Thanks very much!

**Comment by janklocke** [comment]
Thanks for trying out the code and finding the error! You are absolutely right. THe barcode table has been corrected. THe second issue with the loop error still occurred so I added a fix to the script. I hope all issues are resolved. Let me know if you have any other issues. I plan on uploading the original seurat objects we used for the analysis soon. Maybe this will help, too. 
Thanks again, Jan

**Comment by JackieMium** [comment]
@janklocke thanks for your reply and corrections, it really helped clearing the confusion for me.
I am trying out your newest code again.

**Comment by JackieMium** [comment]
Actually, patient ID may still be a problem because in [02_AKI_Urine_Sediment_SO_script.R](https://github.com/janklocke/Urine-single-cell-sequencing-AKI/blob/main/02_AKI_Urine_Sediment_SO_script.R) line 58~59:

```
Pool4 <- subset(Pool4, idents = "P054", invert=T)
Pool6 <- subset(Pool6, idents = c( "FlUriCov116", "FlUriCov118", "FlUriCov120"), invert=T)
```

for `Pool6` the `idents` should be just `c("P116", "p118", "P120")` as per the barcode.csv you provided.

**Comment by janklocke** [comment]
fixed. Thanks @JackieMium!

**Comment by JackieMium** [comment]
> fixed. Thanks @JackieMium!

I am sorry I was not clear in the last reply. Simply changing the 

```
Pool6 <- subset(Pool6, idents = c( "FlUriCov116", "FlUriCov118", "FlUriCov120"), invert=T)
```

won't work because the cells provided  in `URINE_AKI_post_QC_cellnames.rds` are names as `P119_FlUriCov119__TTTCAGTCATGGCTGC-1` or something like this, so for `Pool6` the code will run, but subset still won't work as expected because the cells are differently named.

**Comment by janklocke** [comment]
Sorry it's taking so long. I will need to update the cellnames vector and few parts of the script. Should be up by tuesday.

**Comment by JackieMium** [comment]
> Sorry it's taking so long. I will need to update the cellnames vector and few parts of the script. Should be up by tuesday.

Have been filtering the SO object myself because the cell names issue. I did get similar results though. Looking forward for your updated version of code and data. Thank you.

**Comment by janklocke** [comment]
Instead of providing a cell names list, I made the finished seurat object post-qc available for reference. Thanks again for using and checking our data.

**Comment by JackieMium** [comment]
> Instead of providing a cell names list, I made the finished seurat object post-qc available for reference. Thanks again for using and checking our data.

Great, thanks. I will download the data you uploaded and see if everything goes as expected now.
